# -*- coding: utf-8 -*-
"""Copia de trabajo grupo5 borrador

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJZqMK7a6bGGv-RCnta8AXNBHeetq2PS
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# import plotly.graph_objects as go
# 
# # Configuración inicial de la página
# st.set_page_config(
#     page_title="Monitor de Desigualdad EPH - Corrientes (Grupo 5)",
#     layout="wide",
#     initial_sidebar_state="expanded"
# )
# 
# # -----------------------------------------------------------------------------
# # FASE 1 Y 2: FUNCIONES DE PROCESAMIENTO, GINI, DECILES Y COMPOSICIÓN DE INGRESOS
# # -----------------------------------------------------------------------------
# 
# def procesar_base_eph(df_individual, df_hogar=None, aglomerado=12):
#     """
#     Unifica bases, filtra no-respuestas y prepara el IPCF y fuentes de ingresos.
#     """
#     df = df_individual.copy()
# 
#     # 1. Vinculación con Base Hogar si se proporciona
#     if df_hogar is not None and {'CODUSU', 'NRO_HOGAR'}.issubset(df_hogar.columns):
#         cols_hogar = [c for c in df_hogar.columns if c not in df.columns or c in ['CODUSU', 'NRO_HOGAR']]
#         df = pd.merge(df, df_hogar[cols_hogar], on=['CODUSU', 'NRO_HOGAR'], how='inner')
# 
#     # 2. Filtrado de datos válidos
#     col_decil_nac = 'DECCFR' if 'DECCFR' in df.columns else ('P_DECCF' if 'P_DECCF' in df.columns else None)
#     if col_decil_nac:
#         df = df[~df[col_decil_nac].isin([0, 12, '0', '12'])]
# 
#     # Excluir ingresos IPCF nulos o no respuestas y ponderadores inválidos
#     df = df[(df['IPCF'] > 0) & (df['PONDIH'] > 0)].copy()
# 
#     # 3. Filtro geográfico
#     if aglomerado != 0 and 'AGLOMERADO' in df.columns:
#         df = df[df['AGLOMERADO'] == aglomerado].copy()
# 
#     # Asegurar variables de fuentes de ingresos (Composición)
#     for col in ['P21', 'V2_M', 'V5_M', 'V19_AM']:
#         if col not in df.columns:
#             df[col] = 0
#         else:
#             df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)
#             df[col] = df[col].apply(lambda x: x if x > 0 else 0)
# 
#     return df
# 
# def calcular_gini_trapecio(df, col_ingreso='IPCF', col_ponderador='PONDIH'):
#     """Calcula el Coeficiente de Gini mediante integración trapezoidal."""
#     if df.empty:
#         return 0.0, pd.DataFrame()
# 
#     df_sorted = df.sort_values(by=col_ingreso).copy()
#     poblacion_ponderada = df_sorted[col_ponderador]
#     ingreso_ponderado = df_sorted[col_ingreso] * df_sorted[col_ponderador]
# 
#     X = np.cumsum(poblacion_ponderada) / np.sum(poblacion_ponderada)
#     Y = np.cumsum(ingreso_ponderado) / np.sum(ingreso_ponderada)
# 
#     X = np.insert(X.values, 0, 0.0)
#     Y = np.insert(Y.values, 0, 0.0)
# 
#     dX = np.diff(X)
#     Y_sum = Y[1:] + Y[:-1]
#     area_bajo_lorenz = np.sum(dX * Y_sum) / 2.0
#     coeficiente_gini = 1.0 - (2.0 * area_bajo_lorenz)
# 
#     df_lorenz = pd.DataFrame({'X_poblacion': X, 'Y_ingreso': Y})
#     return coeficiente_gini, df_lorenz
# 
# def calcular_deciles_locales(df, col_ingreso='IPCF', col_ponderador='PONDIH'):
#     """Calcula los deciles locales dividiendo la población ponderada en 10 partes iguales."""
#     if df.empty:
#         return pd.DataFrame()
# 
#     df_sorted = df.sort_values(by=col_ingreso).copy()
#     df_sorted['pob_acum'] = np.cumsum(df_sorted[col_ponderador])
#     pob_total = df_sorted[col_ponderador].sum()
# 
#     df_sorted['decil_local'] = pd.cut(
#         df_sorted['pob_acum'] / pob_total,
#         bins=np.linspace(0, 1, 11),
#         labels=range(1, 11),
#         include_lowest=True
#     )
# 
#     df_sorted['ingreso_total_reg'] = df_sorted[col_ingreso] * df_sorted[col_ponderador]
# 
#     resumen_deciles = df_sorted.groupby('decil_local', observed=False).agg(
#         poblacion=('PONDIH', 'sum'),
#         masa_ingreso=('ingreso_total_reg', 'sum'),
#         ipcf_promedio=(col_ingreso, lambda x: np.average(x, weights=df_sorted.loc[x.index, col_ponderador]))
#     ).reset_index()
# 
#     resumen_deciles['pct_ingreso'] = (resumen_deciles['masa_ingreso'] / df_sorted['ingreso_total_reg'].sum()) * 100
#     return resumen_deciles, df_sorted
# 
# def analizar_composicion_ingresos(df_sorted):
#     """Calcula la estructura del ingreso (Laboral vs Transferencias/Jubilaciones) por decil."""
#     if df_sorted.empty:
#         return pd.DataFrame()
# 
#     # Ponderar componentes
#     df_sorted['ing_laboral_pond'] = df_sorted['P21'] * df_sorted['PONDIH']
#     df_sorted['ing_jubilacion_pond'] = df_sorted['V2_M'] * df_sorted['PONDIH']
#     df_sorted['ing_social_pond'] = df_sorted['V5_M'] * df_sorted['PONDIH']
#     df_sorted['ing_otros_pond'] = df_sorted['V19_AM'] * df_sorted['PONDIH']
# 
#     comp = df_sorted.groupby('decil_local', observed=False).agg(
#         Laboral=('ing_laboral_pond', 'sum'),
#         Jubilaciones_Pensiones=('ing_jubilacion_pond', 'sum'),
#         Asistencia_Social_Subsidios=('ing_social_pond', 'sum'),
#         Otros_Ingresos=('ing_otros_pond', 'sum')
#     ).reset_index()
# 
#     # Convertir a porcentajes de composición
#     cols_ing = ['Laboral', 'Jubilaciones_Pensiones', 'Asistencia_Social_Subsidios', 'Otros_Ingresos']
#     comp['Total_Decil'] = comp[cols_ing].sum(axis=1)
# 
#     for col in cols_ing:
#         comp[f'pct_{col}'] = np.where(comp['Total_Decil'] > 0, (comp[col] / comp['Total_Decil']) * 100, 0)
# 
#     return comp
# 
# def generar_datos_simulados_eph():
#     """Genera una muestra representativa con parámetros de Corrientes (EPH INDEC)."""
#     np.random.seed(42)
#     n = 1200
# 
#     def crear_muestra(mean_log, sigma_log):
#         ipcf = np.random.lognormal(mean=mean_log, sigma=sigma_log, size=n)
#         ponbih = np.random.randint(150, 450, size=n)
# 
#         # Simulación de fuentes de ingreso según vulnerabilidad
#         p21 = ipcf * np.random.uniform(0.5, 0.9, size=n)
#         v5_m = np.where(ipcf < np.percentile(ipcf, 40), np.random.uniform(20000, 80000, size=n), 0)
#         v2_m = np.where(ipcf > np.percentile(ipcf, 50), np.random.uniform(50000, 200000, size=n), 0)
#         v19_am = np.random.uniform(0, 15000, size=n)
# 
#         return pd.DataFrame({
#             'CODUSU': [f'USU_{i}' for i in range(n)],
#             'NRO_HOGAR': 1,
#             'AGLOMERADO': 12,
#             'IPCF': ipcf,
#             'PONDIH': ponbih,
#             'DECCFR': np.random.randint(1, 11, size=n),
#             'P21': p21,
#             'V2_M': v2_m,
#             'V5_M': v5_m,
#             'V19_AM': v19_am
#         })
# 
#     return crear_muestra(11.5, 0.75), crear_muestra(12.1, 0.82)
# 
# # -----------------------------------------------------------------------------
# # FASE 3: INTERFAZ DE DASHBOARD CON STREAMLIT
# # -----------------------------------------------------------------------------
# 
# st.title("📊 Monitor de Distribución del Ingreso y Desigualdad (EPH)")
# st.caption("Proyecto Final - Grupo 5: Andrea Celeste Coronel & Gisela Alejandra Romero | Tecnicatura en Ciencia de Datos e IA")
# 
# st.sidebar.header("⚙️ Configuración y Carga de Datos")
# fuente_datos = st.sidebar.radio("Fuente de Datos:", [
#     "Muestra Oficial EPH (Corrientes)",
#     "Cargar Archivos Excel/CSV",
#     "Cargar desde Google Drive"
# ], index=2) # 'Cargar desde Google Drive' now selected by default
# 
# df_t424, df_t425 = None, None
# 
# if fuente_datos == "Cargar Archivos Excel/CSV":
#     file_2024 = st.sidebar.file_uploader("Base Individual T4 2024", type=["xlsx", "csv"])
#     file_2025 = st.sidebar.file_uploader("Base Individual T4 2025", type=["xlsx", "csv"])
# 
#     if file_2024 and file_2025:
#         df_t424 = pd.read_excel(file_2024) if file_2024.name.endswith('.xlsx') else pd.read_csv(file_2024)
#         df_t425 = pd.read_excel(file_2025) if file_2025.name.endswith('.xlsx') else pd.read_csv(file_2025)
#     else:
#         st.sidebar.info("Cargue ambos períodos para habilitar la auditoría completa.")
#         df_t424, df_t425 = generar_datos_simulados_eph()
# elif fuente_datos == "Cargar desde Google Drive":
#     st.sidebar.markdown("---")
#     st.sidebar.subheader("Rutas de Archivos en Google Drive")
#     # Corrected variable names and added more indicative example paths
#     path_2024 = st.sidebar.text_input("Ruta Base Individual T4 2024 (ej: /content/drive/MyDrive/EPH/EPH_individual_t424.xlsx)", value="/content/drive/MyDrive/EPH/EPH_individual_t424.xlsx")
#     path_2025 = st.sidebar.text_input("Ruta Base Individual T4 2025 (ej: /content/drive/MyDrive/EPH/EPH_individual_t425.xlsx)", value="/content/drive/MyDrive/EPH/EPH_individual_t425.xlsx")
# 
#     if path_2024 and path_2025:
#         try:
#             # Determine file type based on extension (corrected variable names)
#             if path_2024.endswith('.xlsx'):
#                 df_t424 = pd.read_excel(path_2024)
#             elif path_2024.endswith('.csv'):
#                 df_t424 = pd.read_csv(path_2024)
#             else:
#                 st.sidebar.error("Formato de archivo T4 2024 no soportado. Use .xlsx o .csv.")
#                 df_t424 = None
# 
#             if path_2025.endswith('.xlsx'):
#                 df_t425 = pd.read_excel(path_2025)
#             elif path_2025.endswith('.csv'):
#                 df_t425 = pd.read_csv(path_2025)
#             else:
#                 st.sidebar.error("Formato de archivo T4 2025 no soportado. Use .xlsx o .csv.")
#                 df_t425 = None
# 
#             if df_t424 is not None and df_t425 is not None:
#                 st.sidebar.success("Archivos cargados exitosamente desde Google Drive.")
#             else:
#                 st.sidebar.warning("No se pudieron cargar ambos archivos. Se usará la muestra simulada.")
#                 df_t424, df_t425 = generar_datos_simulados_eph()
# 
#         except Exception as e:
#             st.sidebar.error(f"Error al cargar archivos desde Google Drive: {e}. Asegúrese de que las rutas son correctas y Drive está montado. Se usará la muestra simulada.")
#             df_t424, df_t425 = generar_datos_simulados_eph()
#     else:
#         st.sidebar.info("Introduzca las rutas de ambos archivos para cargarlos desde Google Drive.")
#         df_t424, df_t425 = generar_datos_simulados_eph()
# else: # Caso por defecto "Muestra Oficial EPH (Corrientes)"
#     df_t424, df_t425 = generar_datos_simulados_eph()
# 
# aglom_opcion = st.sidebar.selectbox("Aglomerado de Análisis:", ["12 - Corrientes Capital", "Total Nacional (Todos los Aglomerados)"])
# cod_aglomerado = 12 if "12" in aglom_opcion else 0
# 
# # Procesar bases de datos
# df_24_proc = procesar_base_eph(df_t424, aglomerado=cod_aglomerado)
# df_25_proc = procesar_base_eph(df_t425, aglomerado=cod_aglomerado)
# 
# # Cálculos Metodológicos
# gini_24, lorenz_24 = calcular_gini_trapecio(df_24_proc)
# gini_25, lorenz_25 = calcular_gini_trapecio(df_25_proc)
# 
# deciles_24, df_24_sorted = calcular_deciles_locales(df_24_proc)
# deciles_25, df_25_sorted = calcular_deciles_locales(df_25_proc)
# 
# comp_ingresos_25 = analizar_composicion_ingresos(df_25_sorted)
# 
# # Métricas Principales (KPIs)
# col1, col2, col3, col4 = st.columns(4)
# col1.metric("Gini Corrientes T4 2024", f"{gini_24:.4f}")
# diff_gini = gini_25 - gini_24
# col2.metric("Gini Corrientes T4 2025", f"{gini_25:.4f}", delta=f"{diff_gini:+.4f}", delta_color="inverse")
# 
# pob_total_25 = int(df_25_proc['PONDIH'].sum())
# col3.metric("Población Representada", f"{pob_total_25:,} hab.")
# 
# if not deciles_25.empty:
#     d10 = deciles_25.loc[deciles_25['decil_local'] == 10, 'pct_ingreso'].values[0]
#     d1_4 = deciles_25.loc[deciles_25['decil_local'].isin([1, 2, 3, 4]), 'pct_ingreso'].sum()
#     palma_ratio = d10 / d1_4 if d1_4 > 0 else 0
#     col4.metric("Ratio de Palma (T4 2025)", f"{palma_ratio:.2f}x")
# 
# st.markdown("---")
# 
# # Pestañas de Visualización ampliadas según la consigna
# tab1, tab2, tab3, tab4 = st.tabs([
#     "📉 Curva de Lorenz (Gini)",
#     "📊 Deciles Locales y Brechas",
#     "🛡️ Composicion de Ingresos Vulnerables",
#     "🔍 Indicadores de Polarización"
# ])
# 
# with tab1:
#     st.subheader("Curva de Lorenz y Coeficiente de Gini (Método Trapezoidal)")
#     fig_lorenz = go.Figure()
#     fig_lorenz.add_trace(go.Scatter(x=[0, 1], y=[0, 1], mode='lines', name='Equidad Perfecta (45°)', line=dict(dash='dash', color='gray')))
# 
#     step_24 = max(1, len(lorenz_24) // 200)
#     step_25 = max(1, len(lorenz_25) // 200)
# 
#     fig_lorenz.add_trace(go.Scatter(x=lorenz_24['X_poblacion'].iloc[::step_24], y=lorenz_24['Y_ingreso'].iloc[::step_24], mode='lines', name=f'Corrientes T4 2024 (Gini: {gini_24:.4f})', line=dict(color='blue')))
#     fig_lorenz.add_trace(go.Scatter(x=lorenz_25['X_poblacion'].iloc[::step_25], y=lorenz_25['Y_ingreso'].iloc[::step_25], mode='lines', name=f'Corrientes T4 2025 (Gini: {gini_25:.4f})', line=dict(color='red')))
# 
#     fig_lorenz.update_layout(
#         title="Curva de Lorenz sobre Ingreso Per Cápita Familiar (IPCF)",
#         xaxis_title="Proporción Acumulada de la Población (X)",
#         yaxis_title="Proporción Acumulada del Ingreso (Y)",
#         template="plotly_white",
#         height=500
#     )
#     st.plotly_chart(fig_lorenz, use_container_width=True)
# 
# with tab2:
#     st.subheader("Distribución del Ingreso por Decil Local")
#     df_deciles_comp = pd.merge(
#         deciles_24[['decil_local', 'pct_ingreso']].rename(columns={'pct_ingreso': 'T4 2024'}),
#         deciles_25[['decil_local', 'pct_ingreso']].rename(columns={'pct_ingreso': 'T4 2025'}),
#         on='decil_local'
#     )
#     df_deciles_comp['Decil'] = "Decil " + df_deciles_comp['decil_local'].astype(str)
# 
#     fig_bar = px.bar(
#         df_deciles_comp,
#         x='Decil',
#         y=['T4 2024', 'T4 2025'],
#         barmode='group',
#         labels={'value': 'Porcentaje del Ingreso Total (%)', 'variable': 'Período'},
#         title="Participación de cada Decil en la Masa Total de Ingresos"
#     )
#     st.plotly_chart(fig_bar, use_container_width=True)
# 
# with tab3:
#     st.subheader("Estructura y Composición del Ingreso en Hogares Vulnerables (Deciles 1 al 4)")
#     st.write("Análisis detallado sobre las fuentes generadoras del ingreso: Laboral vs. Asistencia Estatal/Subsidios.")
# 
#     if not comp_ingresos_25.empty:
#         comp_vulnerables = comp_ingresos_25[comp_ingresos_25['decil_local'].isin([1, 2, 3, 4])].copy()
#         comp_vulnerables['Decil'] = "Decil " + comp_vulnerables['decil_local'].astype(str)
# 
#         fig_comp = px.bar(
#             comp_vulnerables,
#             x='Decil',
#             y=['pct_Laboral', 'pct_Asistencia_Social_Subsidios', 'pct_Jubilaciones_Pensiones', 'pct_Otros_Ingresos'],
#             title="Composición % del Ingreso por Fuente en los Deciles Más Vulnerables (T4 2025)",
#             labels={'value': 'Porcentaje del Ingreso (%)', 'variable': 'Fuente de Ingreso'},
#             barmode='stack'
#         )
#         st.plotly_chart(fig_comp, use_container_width=True)
# 
#         st.markdown("**Observación Metodológica:** Una alta dependencia de la *Asistencia Social/Subsidios* en los deciles 1 y 2 demuestra la vulnerabilidad del ingreso laboral en la región frente a la informalidad.")
# 
# with tab4:
#     st.subheader("Métricas de Brechas e Ingresos Medios")
# 
#     if not deciles_25.empty:
#         d10_val = deciles_25.loc[deciles_25['decil_local'] == 10, 'pct_ingreso'].values[0]
#         d1_val = deciles_25.loc[deciles_25['decil_local'] == 1, 'pct_ingreso'].values[0]
# 
#         ipcf_d10 = deciles_25.loc[deciles_25['decil_local'] == 10, 'ipcf_promedio'].values[0]
#         ipcf_d1 = deciles_25.loc[deciles_25['decil_local'] == 1, 'ipcf_promedio'].values[0]
# 
#         brecha_masa = d10_val / d1_val if d1_val > 0 else 0
#         brecha_ingreso_medio = ipcf_d10 / ipcf_d1 if ipcf_d1 > 0 else 0
# 
#         c_a, c_b = st.columns(2)
#         with c_a:
#             st.info(f"**Brecha de Masa Acumulada (D10/D1):** {brecha_masa:.2f} veces.")
#             st.write(f"- El **10% más rico (Decil 10)** representa el **{d10_val:.2f}%** del ingreso total.")
#             st.write(f"- El **10% más pobre (Decil 1)** representa el **{d1_val:.2f}%** del ingreso total.")
#         with c_b:
#             st.warning(f"**Brecha de Ingreso Promedio (IPCF D10 / IPCF D1):** {brecha_ingreso_medio:.2f} veces.")
#             st.write(f"- IPCF promedio Decil 10: **${ipcf_d10:,.2f}**")
#             st.write(f"- IPCF promedio Decil 1: **${ipcf_d1:,.2f}**")
#

from google.colab import drive
drive.mount('/content/drive')

!pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# numpy
# plotly
# openpyxl

# 1. Instalar las dependencias
!pip install -r requirements.txt

"""Ahora vamos a ejecutar la aplicación Streamlit en segundo plano. Esto iniciará el servidor de Streamlit."""

import subprocess
import time

# 2. Iniciar la aplicación Streamlit como un proceso en segundo plano
# stdout y stderr son redirigidos para que no saturen la salida de Colab
# Se usa un puerto diferente (8503) para evitar conflictos si el puerto 8502 ya estaba en uso.
print("Iniciando la aplicación Streamlit en segundo plano...")
process = subprocess.Popen(['streamlit', 'run', 'app.py', '--server.port', '8503'],
                           stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE)

# Esperar un momento para que Streamlit se inicie completamente
time.sleep(10) # Aumentado el tiempo de espera a 10 segundos para asegurar el inicio

# Ya no intentamos leer la salida inmediatamente para evitar TimeoutExpired,
# confiando en que el sleep es suficiente para que la app se inicie.
print("Aplicación Streamlit iniciada. Ahora la expondremos a una URL pública.")

"""Finalmente, usaremos `localtunnel` para exponer tu aplicación Streamlit a una URL pública. Haz clic en el enlace generado para acceder a tu dashboard."""

# 3. Exponer la aplicación usando localtunnel

# Instalar localtunnel si no está instalado
!npm install -g localtunnel

# Exponer la aplicación Streamlit que se está ejecutando en el puerto 8503
# Asegúrate de usar el mismo puerto que se usó al iniciar Streamlit
!lt --port 8503

"""### Cómo detener `localtunnel`:

Para detener el proceso de `localtunnel` de forma controlada y liberar el puerto, puedes ejecutar la siguiente celda. Esto es útil si necesitas iniciar un nuevo túnel o si has terminado de usar la aplicación.
"""

# Para detener el proceso en segundo plano (incluyendo localtunnel y streamlit, si se iniciaron como subprocesos)
import os
import signal

# Asumiendo que 'process' es la variable que contiene el Popen object de streamlit
# Y que localtunnel se está ejecutando en la misma celda, su proceso es hijo o está ligado.
# La forma más segura es detener el runtime de Colab o reiniciar el kernel si hay problemas.
# Para localtunnel específicamente, simplemente detener la ejecución de su celda (el botón de stop) es suficiente.
# Si quieres detener el proceso de streamlit:
if 'process' in locals() and process.poll() is None:
    print(f"Deteniendo el proceso Streamlit con PID: {process.pid}")
    process.terminate() # O process.kill() si terminate() no funciona
    process.wait() # Esperar a que el proceso termine
    print("Proceso Streamlit detenido.")
else:
    print("No se encontró un proceso Streamlit activo para detener.")