# -*- coding: utf-8 -*-
"""correccion_TP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMP9aifVL6_4yq06I3-0txmOPL26TTAH
"""

from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import os

# Reemplaza NOMBRE_EXACTO con el nombre real detectado
ruta = '/content/drive/MyDrive/Proceso del trabajo'

# %cd "{ruta}"
!pwd

import os

# Listar los archivos y carpetas dentro de 'Proceso del trabajo'
os.listdir()

!pip install streamlit plotly openpyxl

!pip install streamlit plotly openpyxl -q
!npm install -g localtunnel

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# st.set_page_config(page_title="Gini y Deciles - Corrientes", layout="wide")
# 
# st.title("📊 Desigualdad de Ingresos - Aglomerado Corrientes")
# st.subheader("Coeficiente de Gini y Deciles IPCF (EPH-INDEC)")
# 
# # --- DATOS EXTRAÍDOS DIRECTAMENTE DE TU EXCEL ---
# gini_df = pd.DataFrame({
#     "Período": ["4to Trimestre 2024", "4to Trimestre 2025"],
#     "Gini Corrientes": [0.330571, 0.335805],
#     "Gini Nacional Urbano": [0.430000, 0.427000]
# })
# 
# deciles_2024 = pd.DataFrame({
#     "Decil": list(range(1, 11)),
#     "Población": [38596.0, 36965.0, 42211.0, 37085.0, 40909.0, 38557.0, 38919.0, 40276.0, 39369.0, 39754.0],
#     "IPCF Promedio": [99450.65, 156387.49, 197580.35, 221641.51, 250723.97, 297041.40, 347677.72, 398599.89, 511112.49, 872719.66],
#     "% Ingreso Total": [0.029015, 0.043698, 0.063044, 0.062133, 0.077533, 0.086575, 0.102285, 0.121355, 0.152105, 0.262258]
# })
# 
# deciles_2025 = pd.DataFrame({
#     "Decil": list(range(1, 11)),
#     "Población": [39463.0, 37320.0, 39994.0, 41071.0, 36615.0, 39880.0, 41138.0, 40409.0, 39174.0, 40324.0],
#     "IPCF Promedio": [109085.20, 184462.70, 243511.80, 291700.10, 349467.20, 397317.70, 479657.60, 565244.60, 705537.50, 1072044.00],
#     "% Ingreso Total": [0.024600, 0.039340, 0.055655, 0.068463, 0.073123, 0.090548, 0.112762, 0.130527, 0.157944, 0.247037]
# })
# 
# col1, col2, col3 = st.columns(3)
# col1.metric("Gini Corrientes T4 2024", "0.3306")
# col2.metric("Gini Corrientes T4 2025", "0.3358", delta="0.0052", delta_color="inverse")
# col3.metric("Brecha D10/D1 (T4 2025)", "9.83x", delta="1.05x", delta_color="inverse")
# 
# st.markdown("---")
# st.markdown("### Comparativa Coeficiente de Gini: Corrientes vs. Nacional")
# fig_gini = px.bar(gini_df, x="Período", y=["Gini Corrientes", "Gini Nacional Urbano"], barmode="group")
# st.plotly_chart(fig_gini, width='stretch') # Changed use_container_width=True to width='stretch'
# 
# st.markdown("---")
# periodo = st.radio("Seleccionar Trimestre:", ["4to Trimestre 2024", "4to Trimestre 2025"], horizontal=True)
# df_sel = deciles_2024 if periodo == "4to Trimestre 2024" else deciles_2025
# 
# fig_deciles = px.bar(
#     df_sel, x="Decil", y="% Ingreso Total", text_auto=".2%",
#     title=f"Distribución del Ingreso Total por Decil Local ({periodo})"
# )
# st.plotly_chart(fig_deciles, width='stretch') # Changed use_container_width=True to width='stretch'
#

!curl ipv4.icanhazip.com
!streamlit run app.py & npx localtunnel --port 8501

import os
import signal

# Find and kill any existing Streamlit process
# This command attempts to find processes running 'streamlit run' and kill them.
# It might show an error if no such process is found, which is normal.
!pkill -f "streamlit run"

print('Restarting Streamlit...')
# Start Streamlit again and get a new localtunnel URL
!streamlit run app.py & npx localtunnel --port 8501

# streamlit>=1.30.0
# pandas>=2.0.0
# plotly>=5.18.0